### ISSUE TITLE
Nuxtプロジェクト初期セットアップ

### ISSUE THREAD

**Issue by petaxa** [petaxa/DORTS#35]
## ToDo

- [x] Nuxtのフォルダ構成を一通り作る
- [x] PrimeVueを利用可能にする
- [x] トップ画面の見た目を作成する
- [x] Piniaを利用可能にする
- [x] pinia-plugin-persistedstateを利用可能にする
- [x] Histoireを利用可能にする
- [x] nuxt-test-utilsを利用可能にする
- [x] nuxt-electronを利用可能にし、一度ビルドして確かめる

**Comment by petaxa** [comment]
- [x] Nuxtのフォルダ構成を一通り作る
- [x] PrimeVueを利用可能にする
- [x] トップ画面の見た目を作成する
- [ ] Piniaを利用可能にする
- [ ] pinia-plugin-persistedstateを利用可能にする
- [ ] Histoireを利用可能にする
- [x] nuxt-test-utilsを利用可能にする
- [ ] nuxt-electronを利用可能にし、一度ビルドして確かめる

**Comment by petaxa** [comment]
done
